url: "https://eracom-id471.github.id" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-Jonoboo" # the subpath of your site, e.g. /blog
title: "Yooo" # the name of your site, e.g. ACME Corp.

collections:
  car-crash:
    output: true
  plane-crash:
    output: true



plugins:
  - jekyll-admin
